######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 1 22:25:44 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += layout.cpp
