######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 1 22:14:38 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
