######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 1 23:32:43 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
